export const ApiConstants={
    EMAIL_ALREADY_EXISTS:'Email already exists',
    USERNAME_ALREADY_EXISTS:'Username already exists',
    FAILED_TO_SEND_OTP:'Failed to send OTP',
    USER_CREATED_SUCCESSFULLY:'User created successfully',
    USER_NOT_FOUND:'OTP not found',
    OTP_EXPIRED:'OTP expired',
    INVALID_OTP:'Invalid OTP',
    OTP_VERIFIED_SUCCESSFULLY:'OTP verified successfully',
    USER_DOES_NOT_EXIST:'User does not exist',
    EMAIL_NOT_VERIFIED :'Email not verified',
    WRONG_CREDENTIALS:'Wrong credentials',
    USER_LOGGED_IN_SUCCESSFULLY:'User logged in successfully',
    ADMIN_EXIST:'Admin already exists',
    ADMIN_CREATED:'Admin created successfully',
    CATEGORY_CREATED:'Category created successfully',
    CATEGORY_ALREADY_EXISTS:'Category already exists',
    PRODUCT_CREATED:'Product created successfully',
    CATEGORY_NOT_FOUND:'Category not found'
}